window['Journal'] = {
    "isPopup": false,
    "isPhone": false,
    "isTablet": false,
    "isDesktop": true,
    "filterUrlValuesSeparator": ",",
    "countdownDay": "Day",
    "countdownHour": "Hour",
    "countdownMin": "Min",
    "countdownSec": "Sec",
    "globalPageColumnLeftTabletStatus": false,
    "globalPageColumnRightTabletStatus": false,
    "scrollTop": true,
    "scrollToTop": false,
    "notificationHideAfter": "2000",
    "quickviewPageStyleCloudZoomStatus": true,
    "quickviewPageStyleAdditionalImagesCarousel": false,
    "quickviewPageStyleAdditionalImagesCarouselStyleSpeed": "500",
    "quickviewPageStyleAdditionalImagesCarouselStyleAutoPlay": false,
    "quickviewPageStyleAdditionalImagesCarouselStylePauseOnHover": true,
    "quickviewPageStyleAdditionalImagesCarouselStyleDelay": "3000",
    "quickviewPageStyleAdditionalImagesCarouselStyleLoop": false,
    "quickviewPageStyleAdditionalImagesHeightAdjustment": "5",
    "quickviewPageStylePriceUpdate": true,
    "quickviewPageStyleOptionsSelect": "all",
    "quickviewText": "Quickview",
    "mobileHeaderOn": "tablet",
    "subcategoriesCarouselStyleSpeed": "500",
    "subcategoriesCarouselStyleAutoPlay": false,
    "subcategoriesCarouselStylePauseOnHover": true,
    "subcategoriesCarouselStyleDelay": "3000",
    "subcategoriesCarouselStyleLoop": false,
    "productPageStyleCloudZoomStatus": true,
    "productPageStyleCloudZoomPosition": "inner",
    "productPageStyleAdditionalImagesCarousel": false,
    "productPageStyleAdditionalImagesCarouselStyleSpeed": "500",
    "productPageStyleAdditionalImagesCarouselStyleAutoPlay": true,
    "productPageStyleAdditionalImagesCarouselStylePauseOnHover": true,
    "productPageStyleAdditionalImagesCarouselStyleDelay": "3000",
    "productPageStyleAdditionalImagesCarouselStyleLoop": false,
    "productPageStyleAdditionalImagesHeightAdjustment": "5",
    "productPageStylePriceUpdate": true,
    "productPageStyleOptionsSelect": "all",
    "infiniteScrollStatus": true,
    "infiniteScrollOffset": "2",
    "infiniteScrollLoadPrev": "Load Previous Products",
    "infiniteScrollLoadNext": "Load Next Products",
    "infiniteScrollLoading": "Loading...",
    "infiniteScrollNoneLeft": "You have reached the end of the list.",
    "headerHeight": "100",
    "headerCompactHeight": "60",
    "mobileMenuOn": "",
    "searchStyleSearchAutoSuggestStatus": true,
    "searchStyleSearchAutoSuggestDescription": true,
    "headerMiniSearchDisplay": "default",
    "stickyStatus": true,
    "stickyFullHomePadding": false,
    "stickyFullwidth": true,
    "stickyAt": "300",
    "stickyHeight": "45",
    "headerTopBarHeight": "35",
    "topBarStatus": true,
    "headerType": "classic",
    "headerMobileHeight": "60",
    "headerMobileStickyStatus": true,
    "headerMobileTopBarVisibility": true,
    "headerMobileTopBarHeight": "35",
    "checkoutUrl": "https:\/\/www.journal-theme.com\/5\/index.php?route=checkout\/checkout",
    "notification": [{
        "m": 137,
        "c": "1a2039cc"
    }],
    "headerNotice": [{
        "m": 56,
        "c": "bddc5671"
    }],
    "columnsCount": 2
};